### ISSUE TITLE
incompatibility with spark

### ISSUE THREAD

**Issue by BMayneFactual** [aphyr/clj-antlr#5]
spark 1.6 depends on ST4 4.0.4 https://github.com/apache/spark/blob/branch-1.6/dev/deps/spark-deps-hadoop-2.2#L3

this, however depends on 4.0.8 which includes a value that was added since 4.0.4. Running scarecrow (which you're probably familiar with) on spark, fails in this way: 

```
Caused by: java.lang.NoSuchFieldError: GROUP_FILE_EXTENSION
        at org.antlr.v4.tool.ErrorManager.setFormat(ErrorManager.java:255)
        at org.antlr.v4.Tool.<init>(Tool.java:216)
        at org.antlr.v4.Tool.<init>(Tool.java:211)
        at clj_antlr.interpreted$tool.invoke(interpreted.clj:18)
        at clj_antlr.interpreted$load_string_grammar.invoke(interpreted.clj:26)
        at clj_antlr.interpreted$grammar.invoke(interpreted.clj:38)
        at clj_antlr.interpreted$parser.invoke(interpreted.clj:127)
        at clj_antlr.core$parser.invoke(core.clj:67)
        at scarecrow.parser$antlr_parser.invoke(parser.clj:148)
```

here's the scarecrow side of this: 

``` clojure
(defn antlr-parser [grammar-string]
  (antlr/parser grammar-string {:case-sensitive? false
                                :format transform-antlr-node}))
```

I'm looking into other ways around this problem, but if it's simple for you, ST4 compatibility would be very helpful.

**Comment by aphyr** [comment]
Oh gosh, I actually have no idea what ST4 is and have only a vague understanding of spark's existence.

**Comment by BMayneFactual** [comment]
I think you're getting it through `org.antlr:antlr4:4.2.2`

https://github.com/antlr/antlr4/blob/master/tool/pom.xml

spark is on 3.4.

**Comment by aphyr** [comment]
OK. Sounds like you need to find a different version of spark or antlr, then?

**Comment by aphyr** [comment]
(assuming you can't just exclude the spark version from your build and use the newer one)

**Comment by BMayneFactual** [comment]
right, yeah. I'm going down that route (that's the other ways around this problem). I was just throwing this out on the off chance you knew more and/or had stronger opinions about it than me. I also had no idea what ST4 was until very recently.
